"""L1 entity scanner integration test.

Runs the scanner against the seeded `mock_agent` DB and asserts the shape
of the resulting graph matches what the fixture is meant to produce.

If someone changes the fixture in `mock-agent-project/mongo/dump.json`, these
counts change and this file must be updated deliberately. That's the point —
these are the guard-rails for the L1 contract.
"""

from __future__ import annotations

import pytest

from agentic_visualizer.connectors import MongoConnector
from agentic_visualizer.domain import Graph
from agentic_visualizer.scanners import L1EntityScanner


# Node counts by type — must match the fixture. users + prompts are
# excluded from the current mapping (see l1_entity.py). files are lazy —
# the /graph endpoint no longer emits file nodes, they arrive via
# /graph/subtree on demand.
EXPECTED_NODES_BY_TYPE = {
    "model": 3,
    "tool": 12,   # 10 base + 1 phantom_module_tool + 1 moved_tool (L2 fixture distractors)
    # 11 hand-curated agents (base 3 + 4 orphans + 4 workflow-members) plus
    # 61 generated by seed.py's large_scale_moderation workflow (one
    # coordinator + 60 workers).
    "agent": 11 + 61,
    # 2 hand-curated workflows (research_and_write, nightly_cleanup) plus
    # the generated large_scale_moderation workflow.
    "workflow": 2 + 1,
    # "file": 0 (lazy — fetched via /graph/subtree)
}

# Edge counts by kind. Files are lazy, so no contains edges appear here.
#
# uses breakdown (hand-curated fixture + seed-generated large_scale_moderation):
#   agent → model:  one per agent = 11 hand + 61 generated = 72
#   agent → tool:   hand baseline: 3+3+4 + 2+1+2+1+2+2+3+2 = 25
#                   + 1 for data_analyst gaining phantom_module_tool
#                   + 1 for data_analyst gaining moved_tool
#                   = 27 total from hand-curated agents
#                   generated: coordinator uses 1 shared tool + 60 workers
#                              each use the same shared tool = 61
#   workflow → agent (entrypoint_agent_id): w1 + w3 = 2
#   workflow → agent (agent_ids):
#       w1 has 7, w2 has 0, w3 has 1 coordinator + 60 workers = 68
#   workflow → model (model_ids): w1 has 2, w2 has 1, w3 has 1 = 4
# delegates_to:
#   hand-curated coordinator.sub_agent_ids = 2
#   generated moderation_coordinator.sub_agent_ids = 60
EXPECTED_EDGES_BY_KIND = {
    "uses": 72 + (27 + 61) + 2 + 68 + 4,
    "delegates_to": 2 + 60,
    # "contains": 0 (lazy)
}

# Post-merger count. `Graph.from_results` dedups by (source, target, kind).
# Two collisions get folded here — both workflows that HAVE an entrypoint
# also list that same agent in their agent_ids:
#   w1 (research_and_write)  entrypoint = coordinator, also in agent_ids
#   w3 (large_scale_moderation) entrypoint = moderation_coordinator, also in agent_ids
# So the scanner emits two duplicate `workflow → agent (uses)` pairs and
# the merger collapses each pair to one — total drops by 2.
EXPECTED_MERGED_EDGE_COUNT = sum(EXPECTED_EDGES_BY_KIND.values()) - 2


@pytest.mark.asyncio
async def test_l1_scan_produces_expected_node_counts(
    require_mongo, scan_context_factory
) -> None:
    uri, db = require_mongo
    async with MongoConnector(uri=uri, db_name=db) as connector:
        result = await L1EntityScanner(db_name=db).scan(scan_context_factory(connector))

    by_type: dict[str, int] = {}
    for node in result.nodes:
        by_type[node.type] = by_type.get(node.type, 0) + 1
    assert by_type == EXPECTED_NODES_BY_TYPE, by_type


@pytest.mark.asyncio
async def test_l1_scan_produces_expected_edge_counts(
    require_mongo, scan_context_factory
) -> None:
    uri, db = require_mongo
    async with MongoConnector(uri=uri, db_name=db) as connector:
        result = await L1EntityScanner(db_name=db).scan(scan_context_factory(connector))

    by_kind: dict[str, int] = {}
    for edge in result.edges:
        by_kind[edge.kind] = by_kind.get(edge.kind, 0) + 1
    assert by_kind == EXPECTED_EDGES_BY_KIND, by_kind


@pytest.mark.asyncio
async def test_l1_scan_edges_point_to_real_nodes(
    require_mongo, scan_context_factory
) -> None:
    """No dangling edges — every source/target id must exist as a node."""
    uri, db = require_mongo
    async with MongoConnector(uri=uri, db_name=db) as connector:
        result = await L1EntityScanner(db_name=db).scan(scan_context_factory(connector))
    node_ids = {n.id for n in result.nodes}
    dangling = [
        (e.source_id, e.target_id, e.kind)
        for e in result.edges
        if e.source_id not in node_ids or e.target_id not in node_ids
    ]
    assert not dangling, dangling


@pytest.mark.asyncio
async def test_l1_scan_provenance_is_stable(
    require_mongo, scan_context_factory
) -> None:
    """Two scans with the same clock produce identical node ids and provenance."""
    uri, db = require_mongo
    async with MongoConnector(uri=uri, db_name=db) as c1:
        r1 = await L1EntityScanner(db_name=db).scan(scan_context_factory(c1))
    async with MongoConnector(uri=uri, db_name=db) as c2:
        r2 = await L1EntityScanner(db_name=db).scan(scan_context_factory(c2))

    ids1 = sorted(n.id for n in r1.nodes)
    ids2 = sorted(n.id for n in r2.nodes)
    assert ids1 == ids2


@pytest.mark.asyncio
async def test_l1_merged_graph_deduplicates(require_mongo, scan_context_factory) -> None:
    """Merging the same result twice must not double-count."""
    uri, db = require_mongo
    async with MongoConnector(uri=uri, db_name=db) as connector:
        result = await L1EntityScanner(db_name=db).scan(scan_context_factory(connector))
    graph = Graph.from_results([result, result])
    assert len(graph.nodes) == sum(EXPECTED_NODES_BY_TYPE.values())
    assert len(graph.edges) == EXPECTED_MERGED_EDGE_COUNT
