import { test, expect, request as apiRequest, type Page } from "@playwright/test";
import { appendFileSync } from "node:fs";
import { E2E_TRACE_LOG_PATH } from "./trace-log-path";

/**
 * End-to-end proof that a scripted trace-event stream (our "fake
 * TraceSource" — see Task 4's Verification section) drives the visible
 * overlay: glow on `start`, back to idle on `end`, red ring on `error`
 * persisting until the next `end`, and an unresolvable event landing in the
 * dead-letter drawer. Everything else about this pipeline (store logic,
 * class application) is already covered by the Vitest unit tests in
 * `src/state/runtime.test.ts` and `src/components/EntityNode.test.tsx`;
 * this spec's job is only to prove the real WebSocket + file-tail + DOM
 * wiring holds together end to end.
 *
 * Fixture: `research_agent`'s oid (400000000000000000000001) is the mock
 * Mongo fixture seeded by `mock-agent-project/mongo/dump.json` — stable
 * across runs, not generated by this spec.
 */

const RUN_ID = "e2e-run";

function traceLine(fields: Record<string, unknown>): string {
  return (
    JSON.stringify({
      v: 1,
      ts: new Date().toISOString(),
      run_id: RUN_ID,
      phase: "start",
      kind: "agent",
      ref: { name: "research_agent", module: "src.agents.research_agent" },
      meta: {},
      ...fields,
    }) + "\n"
  );
}

/**
 * React 19's StrictMode (dev only) double-invokes `useRuntimeChannel`'s
 * effect: it opens a WebSocket, immediately tears it down ("closed before
 * the connection is established" — harmless, see runtimeChannel.ts), then
 * opens a second, real one. Asserting on overlay state right after the
 * graph loads can race that dance and append a scripted event before the
 * real socket has subscribed. This tracks every `/ws/runtime` WebSocket the
 * page creates (via an init script, so it's wired before any app code runs)
 * and waits for one to actually reach OPEN, which is the real
 * synchronization point rather than a guessed sleep.
 */
async function trackRuntimeSockets(page: Page): Promise<void> {
  await page.addInitScript(() => {
    (window as unknown as { __runtimeSockets: WebSocket[] }).__runtimeSockets = [];
    const NativeWebSocket = window.WebSocket;
    window.WebSocket = new Proxy(NativeWebSocket, {
      construct(target, args) {
        const url = String(args[0] ?? "");
        const socket = new target(...(args as ConstructorParameters<typeof WebSocket>));
        if (url.includes("/ws/runtime")) {
          (window as unknown as { __runtimeSockets: WebSocket[] }).__runtimeSockets.push(socket);
        }
        return socket;
      },
    });
  });
}

async function waitForOpenRuntimeSocket(page: Page): Promise<void> {
  await page.waitForFunction(
    () =>
      (window as unknown as { __runtimeSockets?: WebSocket[] }).__runtimeSockets?.some(
        (s) => s.readyState === WebSocket.OPEN,
      ) ?? false,
    { timeout: 10_000 },
  );
}

async function loadGraphAndExpandResearchAgent(page: Page): Promise<void> {
  await trackRuntimeSockets(page);
  await page.goto("/");

  // Setup screen defaults to mongodb://localhost:27017 / mock_agent and
  // auto-fetches the schema table; the Continue button is disabled until
  // that fetch resolves.
  const continueButton = page.getByRole("button", { name: /Continue/ });
  await expect(continueButton).toBeEnabled({ timeout: 15_000 });
  await continueButton.click();

  const workflowNode = page.locator(".react-flow__node", { hasText: "Research and Write" });
  await expect(workflowNode).toBeVisible({ timeout: 15_000 });
  await workflowNode.click();

  await expect(researchAgentWrapper(page)).toBeVisible({ timeout: 5_000 });
  await waitForOpenRuntimeSocket(page);
}

/** The node's `--apv-node-color` wrapper div — see `EntityNode.tsx` — is
 *  where `.apv-node-active` / `.apv-node-errored` land. */
function researchAgentWrapper(page: Page) {
  return page.locator('[style*="--apv-node-color"]', { hasText: "Research Agent" });
}

test.beforeAll(async () => {
  // `FileTailTraceSource.start()` schedules its reader task but doesn't
  // await its first iteration -- the task's own first `exists()` check and
  // open-and-seek-to-end happen on a later event-loop tick, not necessarily
  // before the backend's `/health` endpoint (what Playwright's `webServer`
  // waits on) starts responding. `trace-log-path.ts`'s per-run-unique path
  // plus `global-setup.ts` pre-creating it empty already rule out the
  // *content* race this warm-up used to be framed around (see those files'
  // comments for that history and the backend fix it motivated in
  // `file_tail.py`, which is a real capability worth keeping regardless).
  // What's left, and what this still guards, is plain startup-order timing:
  // proving the reader has reached its steady polling state before any real
  // test appends its first event, rather than trusting that several
  // seconds of webServer-readiness-plus-page-load happens to be enough.
  const ctx = await apiRequest.newContext();
  try {
    appendFileSync(
      E2E_TRACE_LOG_PATH,
      traceLine({ span_id: "warmup", kind: "tool", ref: { name: "__e2e_warmup__", module: "pkg.warmup" } }),
    );
    await expect
      .poll(
        async () => {
          const res = await ctx.get("http://127.0.0.1:8765/runtime/dead-letter").catch(() => null);
          if (!res || !res.ok()) return false;
          const entries = (await res.json()) as Array<{ refName: string }>;
          return entries.some((e) => e.refName === "__e2e_warmup__");
        },
        { timeout: 10_000, message: "waiting for FileTailTraceSource to pick up the warm-up event" },
      )
      .toBe(true);
  } finally {
    await ctx.dispose();
  }
});

test.beforeEach(async ({ request }) => {
  // Mongo is a local dev dependency, not something this suite provisions —
  // skip rather than fail red when it's not reachable, mirroring the
  // backend's own `require_mongo` pytest fixture.
  const response = await request
    .get("http://127.0.0.1:8765/schema?uri=mongodb%3A%2F%2Flocalhost%3A27017&db=mock_agent")
    .catch(() => null);
  test.skip(response === null || !response.ok(), "mock_agent Mongo fixture is not reachable");
});

test("node glows on start, returns to idle on end", async ({ page }) => {
  await loadGraphAndExpandResearchAgent(page);
  const node = researchAgentWrapper(page);

  await expect(node).not.toHaveClass(/apv-node-active/);

  appendFileSync(
    E2E_TRACE_LOG_PATH,
    traceLine({ span_id: "span-1", phase: "start", ref: { name: "research_agent", module: "src.agents.research_agent", db_id: "400000000000000000000001" } }),
  );
  await expect(node).toHaveClass(/apv-node-active/, { timeout: 5_000 });

  appendFileSync(
    E2E_TRACE_LOG_PATH,
    traceLine({ span_id: "span-1", phase: "end", ref: { name: "research_agent", module: "src.agents.research_agent", db_id: "400000000000000000000001" } }),
  );
  await expect(node).not.toHaveClass(/apv-node-active/, { timeout: 5_000 });
});

test("node shows a red ring on error and it persists until the next end", async ({ page }) => {
  await loadGraphAndExpandResearchAgent(page);
  const node = researchAgentWrapper(page);
  const ref = { name: "research_agent", module: "src.agents.research_agent", db_id: "400000000000000000000001" };

  appendFileSync(E2E_TRACE_LOG_PATH, traceLine({ span_id: "span-2", phase: "start", ref }));
  await expect(node).toHaveClass(/apv-node-active/, { timeout: 5_000 });

  appendFileSync(
    E2E_TRACE_LOG_PATH,
    traceLine({
      span_id: "span-2",
      phase: "error",
      ref,
      meta: { error: { type: "RuntimeError", message: "e2e-triggered failure", traceback: "Traceback...\nRuntimeError: e2e-triggered failure" } },
    }),
  );
  await expect(node).toHaveClass(/apv-node-errored/, { timeout: 5_000 });
  await expect(node).not.toHaveClass(/apv-node-active/);

  // A second, unrelated span starting AND ending must not clear the ring —
  // only the span that actually caused the error can (see
  // RuntimeStateStore._apply_one: "errored + end(s) -> idle iff ... s was
  // the span that most recently caused the error"). span-2 never got an
  // `end` of its own (it went straight from `start` to `error`), so the
  // ring should still be up after span-3's full lifecycle.
  appendFileSync(E2E_TRACE_LOG_PATH, traceLine({ span_id: "span-3", phase: "start", ref }));
  await page.waitForTimeout(300);
  await expect(node).toHaveClass(/apv-node-errored/);
  appendFileSync(E2E_TRACE_LOG_PATH, traceLine({ span_id: "span-3", phase: "end", ref }));
  await page.waitForTimeout(300);
  await expect(node).toHaveClass(/apv-node-errored/);

  // *Now* end the span that actually broke -- this is what should clear it.
  appendFileSync(E2E_TRACE_LOG_PATH, traceLine({ span_id: "span-2", phase: "end", ref }));
  await expect(node).not.toHaveClass(/apv-node-errored/, { timeout: 5_000 });
});

test("an unresolvable event surfaces in the dead-letter badge and drawer", async ({ page, request }) => {
  await loadGraphAndExpandResearchAgent(page);

  // The dead-letter buffer is process-global, not reset per graph load (see
  // api.ts's `fetchDeadLetterEntries` doc comment) -- this suite's own
  // beforeAll warm-up event already lives in it by the time this test runs,
  // so the baseline count isn't necessarily 0. Read it from the REST
  // endpoint (authoritative, synchronous) rather than the badge: the
  // `dead_letter_stats` WS message is only pushed on the channel's periodic
  // broadcast tick, not included in the initial snapshot on connect, so the
  // badge can still show a stale count for a moment right after page load.
  const badge = page.getByRole("button", { name: /Dead letters/ });
  const baselineEntries = (await (await request.get("http://127.0.0.1:8765/runtime/dead-letter")).json()) as unknown[];
  const baselineCount = baselineEntries.length;

  appendFileSync(
    E2E_TRACE_LOG_PATH,
    traceLine({
      span_id: "span-dl-1",
      kind: "tool",
      ref: { name: "e2e_nonexistent_tool", module: "pkg.nowhere" },
    }),
  );

  await expect(badge).toContainText(String(baselineCount + 1), { timeout: 5_000 });
  await badge.click();
  // Exact match: "e2e_nonexistent_tool" alone is also a substring of the
  // entry's `reason` line (the TraceRef repr), so a plain substring
  // getByText resolves to two elements and Playwright's strict mode rejects
  // it. The "kind · refName" line is the one meant to uniquely identify a
  // row -- match that exactly instead.
  await expect(page.getByText("tool · e2e_nonexistent_tool", { exact: true })).toBeVisible();
});
